### ISSUE TITLE
[Feature request] Upload to crates.io?

### ISSUE THREAD

**Issue by thomasaarholt** [ElectrifyPro/cas-rs#4]
### Description

I was just looking for a CAS solution for simplifying algebraic equations for a small exploration project, and it looks like cas-rs (specifically the cas-compute crate) would do what I want. 

Have you considered uploading it to crates.io? It would be nice for projects like these to be available there so that one can simply do `cargo add cas-compute` in one's project.

**Comment by ElectrifyPro** [comment]
Yes, I'd be happy to publish `cas-compute` to crates.io! I've never published crates before, so there's going to be a learning curve for me. I would also like to have good documentation first before publishing. In the meantime, you and anyone can add this to your `Cargo.toml` to use `cas-compute` locally:

```toml
[dependencies.cas-compute]
git = "https://github.com/ElectrifyPro/cas-rs.git"
branch = "main"
```
